app:
  resource: "@SuplaBundle/Resources/config/routing.yml"

api:
  resource: "@SuplaApiBundle/Resources/config/routing.yml"

webapi:
  type: rest
  defaults: {_format: json}
  resource: "@SuplaWebApiBundle/Resources/config/routing.yml"

logout:
  path: /auth/logout

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api-docs
